IMAGE_NAME = "ubuntu/focal64"
# IMAGE_VERSION = "1.0.282"
CLIENT_NODE_NUMBER = 1
PROVIDER = "libvirt"

Vagrant.configure("2") do |config|
    # config.ssh.insert_key = false

    config.vm.provider PROVIDER do |v|
        v.memory = 4096
        v.cpus = 2
    end
      
    config.vm.define "controleplain" do |master|
        master.vm.boot_timeout = 300
        master.vm.box = IMAGE_NAME
        master.vm.network "public_network", bridge: "Realtek USB FE Family Controller", ip: "192.168.0.10"
        master.vm.hostname = "controleplain"
        master.vm.synced_folder ".", "/vagrant", disabled: true
        #master.vm.provision "shell", path: "create_user.sh"
    end

    (1..CLIENT_NODE_NUMBER).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.boot_timeout = 300
            node.vm.box = IMAGE_NAME
            node.vm.synced_folder ".", "/vagrant", disabled: true
            # node.vm.box_version = IMAGE_VERSION
            # node.vm.network "public_network", ip: "192.168.50.#{i + 10}", bridge: "Hyper-V Virtual Ethernet Adapter"
            node.vm.network "public_network", bridge: "Realtek USB FE Family Controller", ip: "192.168.0.#{i + 10}"
            node.vm.hostname = "node-#{i}"
            #node.vm.provision "shell", path: "create_user.sh"
            node.vm.provider PROVIDER do |nodevm|
              nodevm.memory = 1024
              nodevm.cpus = 1
            end
        end
    end
end
