- name: Configure aerospike cluster
  hosts: all
  vars:
    REPO_GPG_CHECK: 0
    AS_VERSION_PATH_MAJOR: "6.2.0.0"
    AS_VERSION_PATH_MINOR: aerospike-server-community_6.2.0.0_tools-8.0.2_el8_x86_64
    CLUSTER_NODES: 
      - 192.168.166.180
      - 192.168.166.181
      - 192.168.166.182
  roles:
    - { role: roles/aerospike }