IMAGE_NAME = "generic/oracle8"
PROVIDER = "virtualbox"
DISK_SIZE="10GB"

servers = [
  { :hostname => "aerospike-01", :ip => "192.168.166.180" },
  { :hostname => "aerospike-02", :ip => "192.168.166.181" },
  { :hostname => "aerospike-03", :ip => "192.168.166.182" },
  { :hostname => "aerospike-04", :ip => "192.168.166.183" },
  { :hostname => "aerospike-05", :ip => "192.168.166.184" },
  { :hostname => "aerospike-06", :ip => "192.168.166.185" }
]

Vagrant.configure("2") do |config|
    servers.each do |i|
        config.vm.define i[:hostname] do |node|
            node.vm.boot_timeout = 300
            node.vm.box = IMAGE_NAME
            node.vm.synced_folder ".", "/vagrant", disabled: true
            node.vm.network "public_network", ip: i[:ip], bridge: "enp37s0", dev: "enp37s0"
            node.vm.hostname = i[:hostname]
            node.vm.provision "file", source: "../temp/sshkey.pub", destination: "./sshkey.pub"
            node.vm.provision "file", source: "../temp/sshkey", destination: "./sshkey"
            node.vm.provision "shell", path: "../common_scripts/user.sh"
            node.vm.provision "shell", path: "../common_scripts/dns_config.sh"
            node.vm.provision "shell", path: "../common_scripts/other_configs.sh"
            node.vm.disk :disk, size: DISK_SIZE, primary: true
            node.vm.provider PROVIDER do |nodevm|
              nodevm.memory = 2048
              nodevm.cpus = 2
            end
            if i[:hostname] == "aerospike-01"
              node.vm.provision :ansible do |ansible|
                ansible.playbook = "playbook.yml"
                ansible.limit = "all"
                ansible.raw_arguments  = [
                  "--private-key=../temp/sshkey",
                  "--become",
                  "--become-user=root"
                ]
              end
            end
        end
    end
end
