PROVIDER = "virtualbox"
IMAGE_NAME = "generic/ubuntu2004"
DISK_SIZE="10GB"

servers = [
  { :hostname => "test", :ip => "192.168.166.160" , :cpu => 2, :memory => 2048 }
]

Vagrant.configure("2") do |config|
    servers.each do |i|
        config.vm.define i[:hostname] do |node|
            node.vm.boot_timeout = 300
            node.vm.box = IMAGE_NAME
            node.vm.synced_folder ".", "/vagrant", disabled: true
            node.vm.network "public_network", ip: i[:ip], bridge: "enp37s0", dev: "enp37s0"
            node.vm.hostname = i[:hostname]
            node.vm.provision "file", source: "../temp/sshkey.pub", destination: "./sshkey.pub"
            node.vm.provision "file", source: "../temp/sshkey", destination: "./sshkey"
            node.vm.provision "shell", path: "../common_scripts/user.sh"
            node.vm.provision "shell", path: "../common_scripts/dns_config.sh"
            node.vm.disk :disk, size: DISK_SIZE, primary: true
            node.vm.provider PROVIDER do |nodevm|
              nodevm.memory = i[:memory]
              nodevm.cpus = i[:cpu]
            end
        end
    end
end
