---
all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    nfs_server_addr: "gitlab.local.com"
    nfs_server_path: "/nfs_data"
  children:
    master:
      hosts:
        control-plane-1.local.com:
          host_role: master-control-plane
        control-plane-2.local.com:
          host_role: slave-control-plane
        control-plane-3.local.com:
          host_role: slave-control-plane
    worker:
      hosts:
        worker-1.local.com:
          host_role: worker
        worker-2.local.com:
          host_role: worker
        worker-3.local.com:
          host_role: worker
    postgres:
      hosts:
        db-1.local.com:
          host_role: postgres_master
        db-2.local.com:
          host_role: postgres_slave
    # nfs:
    #   hosts:
    #     gitlab.local.com:
