VM_NAME = "dns"
PROVIDER = "virtualbox"
IMAGE_NAME = "generic/ubuntu2004"

Vagrant.configure("2") do |config|
    # config.ssh.insert_key = false

    config.vm.provider PROVIDER do |v|
        v.memory = 1024
        v.cpus = 1
    end
    
    config.vm.define VM_NAME do |master|
        master.vm.boot_timeout = 300
        master.vm.box = IMAGE_NAME
        master.vm.network "public_network", ip: "192.168.0.201", bridge: "wlp2s0", dev: "wlp2s0"
        master.vm.hostname = VM_NAME
        master.vm.synced_folder ".", "/vagrant", disabled: true
        master.vm.provision "file", source: "../temp/sshkey.pub", destination: "./sshkey.pub"
        master.vm.provision "file", source: "../temp/sshkey", destination: "./sshkey"
        master.vm.provision "shell", path: "../common_scripts/user.sh"
        master.vm.provision "shell", path: "../common_scripts/dns_config.sh"
    end

end
